project:
  type: website
  output-dir: docs

website:
  title: "Pranay's Data Science Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/pranaysen
      - icon: linkedin
        href: https://www.linkedin.com/in/pranay-sen/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

